// Shared weather data for all themes.
// Three locations with mixed conditions: sun, rain, snow.

const WEATHER_DATA = [
  {
    id: "lis",
    city: "Lisbon",
    region: "Portugal",
    country: "PT",
    tz: "WEST",
    localTime: "14:32",
    lat: 38.72,
    lon: -9.14,
    condition: "clear",
    conditionLabel: "Clear sky",
    tempF: 74, tempC: 23,
    feelsF: 76, feelsC: 24,
    highF: 78, highC: 26,
    lowF: 61, lowC: 16,
    humidity: 48,
    wind: { speedMph: 9, speedKph: 14, dir: "NW", deg: 315 },
    pressure: 1021,
    visibility: 16,
    uv: 7,
    sunrise: "06:51",
    sunset: "20:18",
    precip: 0,
    dewF: 54,
    hourly: [
      { t: "14", tF: 74, tC: 23, cond: "clear", pop: 0 },
      { t: "15", tF: 76, tC: 24, cond: "clear", pop: 0 },
      { t: "16", tF: 77, tC: 25, cond: "clear", pop: 0 },
      { t: "17", tF: 78, tC: 26, cond: "clear", pop: 0 },
      { t: "18", tF: 76, tC: 24, cond: "fewclouds", pop: 5 },
      { t: "19", tF: 73, tC: 23, cond: "fewclouds", pop: 5 },
      { t: "20", tF: 70, tC: 21, cond: "fewclouds", pop: 0 },
      { t: "21", tF: 67, tC: 19, cond: "clear", pop: 0 },
      { t: "22", tF: 65, tC: 18, cond: "clear", pop: 0 },
      { t: "23", tF: 63, tC: 17, cond: "clear", pop: 0 },
      { t: "00", tF: 62, tC: 17, cond: "clear", pop: 0 },
      { t: "01", tF: 61, tC: 16, cond: "clear", pop: 0 },
    ],
    daily: [
      { d: "Today", cond: "clear", hiF: 78, hiC: 26, loF: 61, loC: 16, pop: 0 },
      { d: "Sat",   cond: "clear", hiF: 80, hiC: 27, loF: 63, loC: 17, pop: 0 },
      { d: "Sun",   cond: "fewclouds", hiF: 77, hiC: 25, loF: 62, loC: 17, pop: 10 },
      { d: "Mon",   cond: "fewclouds", hiF: 74, hiC: 23, loF: 60, loC: 16, pop: 20 },
      { d: "Tue",   cond: "rain",  hiF: 68, hiC: 20, loF: 58, loC: 14, pop: 70 },
      { d: "Wed",   cond: "rain",  hiF: 66, hiC: 19, loF: 57, loC: 14, pop: 65 },
      { d: "Thu",   cond: "clear", hiF: 72, hiC: 22, loF: 58, loC: 14, pop: 10 },
    ],
  },
  {
    id: "edi",
    city: "Edinburgh",
    region: "Scotland",
    country: "UK",
    tz: "BST",
    localTime: "14:32",
    lat: 55.95,
    lon: -3.19,
    condition: "rain",
    conditionLabel: "Steady rain",
    tempF: 52, tempC: 11,
    feelsF: 48, feelsC: 9,
    highF: 55, highC: 13,
    lowF: 44, lowC: 7,
    humidity: 88,
    wind: { speedMph: 18, speedKph: 29, dir: "SW", deg: 225 },
    pressure: 998,
    visibility: 6,
    uv: 2,
    sunrise: "05:48",
    sunset: "21:33",
    precip: 0.42,
    dewF: 48,
    hourly: [
      { t: "14", tF: 52, tC: 11, cond: "rain", pop: 85 },
      { t: "15", tF: 52, tC: 11, cond: "rain", pop: 90 },
      { t: "16", tF: 51, tC: 11, cond: "rain", pop: 95 },
      { t: "17", tF: 51, tC: 11, cond: "rain", pop: 85 },
      { t: "18", tF: 50, tC: 10, cond: "drizzle", pop: 60 },
      { t: "19", tF: 50, tC: 10, cond: "drizzle", pop: 55 },
      { t: "20", tF: 49, tC: 9,  cond: "cloudy", pop: 30 },
      { t: "21", tF: 48, tC: 9,  cond: "cloudy", pop: 20 },
      { t: "22", tF: 47, tC: 8,  cond: "cloudy", pop: 15 },
      { t: "23", tF: 46, tC: 8,  cond: "cloudy", pop: 10 },
      { t: "00", tF: 45, tC: 7,  cond: "cloudy", pop: 5 },
      { t: "01", tF: 44, tC: 7,  cond: "cloudy", pop: 5 },
    ],
    daily: [
      { d: "Today", cond: "rain",  hiF: 55, hiC: 13, loF: 44, loC: 7, pop: 90 },
      { d: "Sat",   cond: "rain",  hiF: 54, hiC: 12, loF: 43, loC: 6, pop: 80 },
      { d: "Sun",   cond: "cloudy",hiF: 56, hiC: 13, loF: 45, loC: 7, pop: 40 },
      { d: "Mon",   cond: "fewclouds", hiF: 58, hiC: 14, loF: 46, loC: 8, pop: 20 },
      { d: "Tue",   cond: "cloudy",hiF: 57, hiC: 14, loF: 46, loC: 8, pop: 30 },
      { d: "Wed",   cond: "rain",  hiF: 53, hiC: 12, loF: 44, loC: 7, pop: 70 },
      { d: "Thu",   cond: "rain",  hiF: 51, hiC: 11, loF: 42, loC: 6, pop: 85 },
    ],
  },
  {
    id: "rej",
    city: "Reykjavík",
    region: "Iceland",
    country: "IS",
    tz: "GMT",
    localTime: "13:32",
    lat: 64.15,
    lon: -21.94,
    condition: "snow",
    conditionLabel: "Light snow",
    tempF: 28, tempC: -2,
    feelsF: 19, feelsC: -7,
    highF: 31, highC: -1,
    lowF: 22, lowC: -6,
    humidity: 76,
    wind: { speedMph: 22, speedKph: 35, dir: "N", deg: 0 },
    pressure: 1008,
    visibility: 3,
    uv: 1,
    sunrise: "07:12",
    sunset: "18:44",
    precip: 0.18,
    dewF: 22,
    hourly: [
      { t: "13", tF: 28, tC: -2, cond: "snow", pop: 80 },
      { t: "14", tF: 28, tC: -2, cond: "snow", pop: 85 },
      { t: "15", tF: 27, tC: -3, cond: "snow", pop: 90 },
      { t: "16", tF: 27, tC: -3, cond: "snow", pop: 85 },
      { t: "17", tF: 26, tC: -3, cond: "snow", pop: 75 },
      { t: "18", tF: 25, tC: -4, cond: "snow", pop: 60 },
      { t: "19", tF: 24, tC: -4, cond: "cloudy", pop: 30 },
      { t: "20", tF: 23, tC: -5, cond: "cloudy", pop: 20 },
      { t: "21", tF: 22, tC: -6, cond: "cloudy", pop: 15 },
      { t: "22", tF: 22, tC: -6, cond: "fewclouds", pop: 10 },
      { t: "23", tF: 21, tC: -6, cond: "fewclouds", pop: 5 },
      { t: "00", tF: 21, tC: -6, cond: "fewclouds", pop: 0 },
    ],
    daily: [
      { d: "Today", cond: "snow",  hiF: 31, hiC: -1, loF: 22, loC: -6, pop: 85 },
      { d: "Sat",   cond: "snow",  hiF: 29, hiC: -2, loF: 20, loC: -7, pop: 75 },
      { d: "Sun",   cond: "cloudy",hiF: 33, hiC: 1,  loF: 24, loC: -4, pop: 30 },
      { d: "Mon",   cond: "clear", hiF: 35, hiC: 2,  loF: 25, loC: -4, pop: 10 },
      { d: "Tue",   cond: "fewclouds", hiF: 34, hiC: 1, loF: 24, loC: -4, pop: 15 },
      { d: "Wed",   cond: "snow",  hiF: 30, hiC: -1, loF: 21, loC: -6, pop: 70 },
      { d: "Thu",   cond: "snow",  hiF: 28, hiC: -2, loF: 19, loC: -7, pop: 80 },
    ],
  },
];

// Searchable city pool for the "add location" flow
const CITY_POOL = [
  { city: "Tokyo",       region: "Japan",       country: "JP", condition: "fewclouds", tempF: 68, tempC: 20 },
  { city: "Marrakesh",   region: "Morocco",     country: "MA", condition: "clear",     tempF: 89, tempC: 32 },
  { city: "Buenos Aires",region: "Argentina",   country: "AR", condition: "clear",     tempF: 72, tempC: 22 },
  { city: "Bergen",      region: "Norway",      country: "NO", condition: "rain",      tempF: 47, tempC: 8 },
  { city: "Hanoi",       region: "Vietnam",     country: "VN", condition: "rain",      tempF: 82, tempC: 28 },
  { city: "Ushuaia",     region: "Argentina",   country: "AR", condition: "snow",      tempF: 34, tempC: 1 },
  { city: "Cairo",       region: "Egypt",       country: "EG", condition: "clear",     tempF: 94, tempC: 34 },
  { city: "Helsinki",    region: "Finland",     country: "FI", condition: "snow",      tempF: 27, tempC: -3 },
  { city: "Cape Town",   region: "South Africa",country: "ZA", condition: "fewclouds", tempF: 70, tempC: 21 },
  { city: "Mumbai",      region: "India",       country: "IN", condition: "cloudy",    tempF: 86, tempC: 30 },
  { city: "Quito",       region: "Ecuador",     country: "EC", condition: "drizzle",   tempF: 64, tempC: 18 },
  { city: "Reykjanes",   region: "Iceland",     country: "IS", condition: "snow",      tempF: 26, tempC: -3 },
];

window.WEATHER_DATA = WEATHER_DATA;
window.CITY_POOL = CITY_POOL;
